name: 01 - Building Blocks


#on: [push] and workflow_dispatch are event triggers that determine when your workflow should run.

##on: [push]
####This trigger runs the workflow whenever a push is made to the repository. You can specify branches or tags to narrow down when the workflow should be triggered.
on: 
  push:

###This trigger allows you to manually trigger the workflow from the GitHub Actions tab in your repository.
#on:
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: 'Environment to deploy to'
#        required: true
#        default: 'production'


jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Say Hello"

  echo-goodbye:
    runs-on: ubuntu:latest
    steps: 
      - name: Failed Step
        run: |
          echo "It will fail"
          exit 1
      - name: Say GoodBye
        run: echo "Good Bye"
 
