name: 02-workflow-events

on: 
  push:
  pull_request: 
  schedule: 
    - cron: '*/5 * * * *'
  workflow_dispatch: 

jobs: 
  echo: 
    runs-on: ubuntu-latest 
    steps: 
      - name: show the trigger t0 me
        run: echo "I've been triggered by a(n) ${{github.event_name}}" ##pinnt the event that trigger name. 
